Repository graasp/graasp, pull requests merged in 2022-12, with the labels that each got.

#285 chore: add release-please
  .github/workflows/release-please.yml
Labels: chore

#288 feat: implement DB read replicas
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/cintegration-ecs-backend-caller.yml
  README.md
  src/app.ts
  src/plugins/database.ts
  src/util/config.ts
Labels: feature

#290 fix: correctly assign interceptors when undefined
  src/plugins/database.ts
  test/plugins/database.test.ts
Labels: bug
