Repository graasp/graasp, pull requests merged in 2023-07, with the labels that each got.

#360 fix: replace and document usage of decorateRequest
  package.json
  src/plugins/decorator.ts
  src/sentry.ts
  src/services/auth/plugins/mobile/index.ts
  src/services/item/plugins/app/index.ts
  yarn.lock
Labels: bug :beetle:

#466 fix: return root published item when querying for a child item
  .gitignore
  src/services/item/plugins/itemTag/repository.ts
  src/services/item/plugins/published/repositories/itemPublished.ts
  src/services/item/plugins/published/test/index.test.ts
Labels: bug :beetle:

#483 fix: item relation can be null because of soft-delete
  package.json
  src/services/invitation/repository.ts
  src/services/invitation/test/index.test.ts
  src/services/item/plugins/app/appAction/appAction.ts
  src/services/item/plugins/app/appAction/repository.ts
  src/services/item/plugins/itemFavorite/repositories/favorite.ts
  src/services/item/plugins/itemFavorite/test/index.test.ts
  src/services/item/plugins/itemLike/repository.ts
  src/services/item/plugins/itemLike/test/index.test.ts
  src/services/item/plugins/published/repositories/itemPublished.ts
  src/services/item/plugins/published/schemas.ts
  src/services/item/plugins/published/service.ts
  src/services/item/plugins/published/test/index.test.ts
  yarn.lock
Labels: bug :beetle:

#492 fix: remove duplicate public tag in migration
  src/migrations/1689666251815-clean-tags.ts
  test/migrations/migrations1689666251815/fixture.ts
  test/migrations/migrations1689666251815/migrations.test.ts
Labels: bug :beetle:

#486 fix: login-password to use a redirect with the token in query string
  README.md
  src/services/auth/plugins/mobile/index.ts
  src/services/auth/plugins/mobile/mobile.test.ts
  src/utils/config.ts
Labels: chore

#484 fix: fix detachedMoveHousekeeping to move to root
  .github/workflows/deploy-refactor.yml
  src/services/item/test/index.test.ts
  src/services/itemMembership/repository.ts
  yarn.lock
Labels: bug :beetle:

#507 fix: allow multiple extra and settings fields on update
  .github/workflows/test.yml
  src/migrations/1689777747530-default-item-settings.ts
  src/services/item/plugins/document/document.test.ts
  src/services/item/plugins/document/schemas.ts
  src/services/item/repository.ts
  test/migrations/migrations1689666251815/migrations.test.ts
  test/migrations/migrations1689777747530/fixture.ts
  test/migrations/migrations1689777747530/migrations.test.ts
Labels: bug :beetle:

#508 chore: load git bash completions in devcontainer
  .devcontainer/Dockerfile
Labels: chore

#502 fix: add creator in recent and liked collections
  src/services/item/plugins/published/repositories/itemPublished.ts
Labels: bug :beetle:

#505 504 fix app data reader
  package.json
  src/services/authorization.ts
  src/services/item/plugins/app/appAction/repository.ts
  src/services/item/plugins/app/appData/appData.ts
  src/services/item/plugins/app/appData/errors.ts
  src/services/item/plugins/app/appData/index.ts
  src/services/item/plugins/app/appData/repository.ts
  src/services/item/plugins/app/appData/schemas.ts
  src/services/item/plugins/app/appData/service.ts
  src/services/item/plugins/app/appData/test/index.test.ts
  src/services/item/plugins/published/test/index.test.ts
  test/migrations/migrations1689777747530/migrations.test.ts
  yarn.lock
Labels: bug :beetle:, priority

#496 fix: improve import zip, fix undefined parent
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/deploy-development.yml
  src/server.ts
  src/services/item/plugins/file/service.ts
  src/services/item/plugins/importExport/index.ts
  src/services/item/plugins/importExport/service.ts
  src/services/item/plugins/importExport/test/fixtures/app.url
  src/services/item/plugins/importExport/test/fixtures/app.url.description.html
  src/services/item/plugins/importExport/test/fixtures/archive.ts
  src/services/item/plugins/importExport/test/fixtures/archive.zip
  src/services/item/plugins/importExport/test/fixtures/document.graasp
  src/services/item/plugins/importExport/test/fixtures/document.graasp.description.html
  src/services/item/plugins/importExport/test/fixtures/empty.zip
  src/services/item/plugins/importExport/test/fixtures/fixtureUtils.ts
  src/services/item/plugins/importExport/test/fixtures/folder.description.html
  src/services/item/plugins/importExport/test/fixtures/folder/somefile
  src/services/item/plugins/importExport/test/fixtures/img.png
  src/services/item/plugins/importExport/test/fixtures/img.png.description.html
  src/services/item/plugins/importExport/test/fixtures/img_no_extension
  src/services/item/plugins/importExport/test/fixtures/link.url
  src/services/item/plugins/importExport/test/fixtures/link.url.description.html
  src/services/item/plugins/importExport/test/fixtures/parentFolder.description.html
  src/services/item/plugins/importExport/test/index.test.ts
  src/services/item/plugins/importExport/utils.test.ts
  src/services/item/plugins/importExport/utils.ts
  src/services/itemMembership/repository.ts
  src/services/itemMembership/service.ts
  src/utils/config.ts
Labels: bug :beetle:

#522 fix: copied item should not inherit public tag from original
  src/services/item/plugins/itemLike/itemLike.ts
  src/services/item/plugins/itemTag/index.ts
  src/services/item/plugins/itemTag/repository.ts
Labels: bug :beetle:

#524 fix: add creator in getPublishedItemsByCategories
  src/services/item/plugins/published/repositories/itemPublished.ts
Labels: bug :beetle:
