Repository graasp/graasp, pull requests merged in 2023-10, with the labels that each got.

#623 feat: add indices on action entity
  src/migrations/1695655073720-gist-action-path.ts
  src/plugins/database.ts
  src/sentry.ts
  src/services/action/entities/action.ts
  src/services/action/repositories/action.ts
  src/utils/errors.ts
  test/migrations/migrations1679669193721/migrations.test.ts
  test/migrations/migrations1679669193721/migrations1679669193721.fixtures.ts
  test/migrations/migrations1683637099103/migrations.test.ts
  test/migrations/migrations1689666251815/migrations.test.ts
Labels: priority

#640 fix(types): fileStream argument has incompatible typing
  src/services/file/repositories/s3.ts
Labels: bug :beetle:

#552 feat: add websockets feedbacks
  src/app.ts
  src/services/authorization.ts
  src/services/item/controller.ts
  src/services/item/plugins/action/index.ts
  src/services/item/plugins/action/requestExport/service.ts
  src/services/item/plugins/action/test/ws.test.ts
  src/services/item/plugins/published/plugins/search/service.ts
  src/services/item/plugins/recycled/index.ts
  src/services/item/plugins/recycled/service.ts
  src/services/item/plugins/recycled/test/index.test.ts
  src/services/item/plugins/recycled/test/ws.test.ts
  src/services/item/plugins/recycled/ws/events.ts
  src/services/item/plugins/recycled/ws/hooks.ts
  src/services/item/plugins/validation/index.ts
  src/services/item/plugins/validation/service.ts
  src/services/item/plugins/validation/test/index.test.ts
  src/services/item/plugins/validation/test/utils.ts
  src/services/item/plugins/validation/test/ws.test.ts
  src/services/item/repository.ts
  src/services/item/service.ts
  src/services/item/test/index.test.ts
  src/services/item/test/ws.test.ts
  src/services/item/ws/events.ts
  src/services/item/ws/hooks.ts
  src/services/itemMembership/repository.ts
  src/services/itemMembership/test/ws.test.ts
  src/services/itemMembership/ws/events.ts
  src/services/itemMembership/ws/hooks.ts
  src/services/websockets/service-api.ts
  src/services/websockets/test/test-utils.ts
  src/services/websockets/test/test-websocket-client.ts
  src/services/websockets/test/ws-app.ts
Labels: feature

#655 fix: add local test db
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/workflows/test.yml
  package.json
  src/plugins/__mocks__/datasource.ts
  src/server.ts
  src/services/item/utils.ts
  src/services/member/plugins/thumbnail/schemas.ts
  src/utils/config.ts
  test/app.ts
Labels: chore, testing

#652 docs: update readme instructions for localstack
  README.md
Labels: documentation

#662 fix: set member id on post app data
  src/services/item/plugins/app/appData/repository.ts
  src/services/item/plugins/app/appData/schemas.ts
  src/services/item/plugins/app/appData/service.ts
  src/services/item/plugins/app/appData/test/index.test.ts
Labels: bug :beetle:

#653 fix: add missing relations in appSettings
  src/services/item/plugins/app/appSetting/repository.ts
Labels: bug :beetle:

#580 fix(internal): better type safety
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .eslintrc
  .github/workflows/test.yml
  package.json
  src/services/action/entities/action.ts
  src/services/chat/chatMessage.ts
  src/services/chat/plugins/mentions/chatMention.ts
  src/services/invitation/invitation.ts
  src/services/item/entities/Item.ts
  src/services/item/plugins/app/appAction/appAction.ts
  src/services/item/plugins/app/appAction/service.ts
  src/services/item/plugins/app/appData/appData.ts
  src/services/item/plugins/app/appSetting/appSettings.ts
  src/services/item/plugins/app/service.ts
  src/services/item/plugins/app/ws/events.ts
  src/services/item/plugins/document/document.test.ts
  src/services/item/plugins/document/index.ts
  src/services/item/plugins/embeddedLink/index.ts
  src/services/item/plugins/etherpad/service.ts
  src/services/item/plugins/etherpad/test/service-api.test.ts
  src/services/item/plugins/file/index.ts
  src/services/item/plugins/file/service.ts
  src/services/item/plugins/html/h5p/test/plugin.test.ts
  src/services/item/plugins/html/h5p/types.ts
  src/services/item/plugins/importExport/service.ts
  src/services/item/plugins/importExport/test/fixtures/archive.ts
  src/services/item/plugins/importExport/test/index.test.ts
  src/services/item/plugins/importExport/utils.ts
  src/services/item/plugins/itemCategory/entities/ItemCategory.ts
  src/services/item/plugins/itemFlag/itemFlag.ts
  src/services/item/plugins/itemTag/ItemTag.ts
  src/services/item/plugins/published/entities/itemPublished.ts
  src/services/item/plugins/recycled/RecycledItemData.ts
  src/services/item/plugins/thumbnail/index.ts
  src/services/item/plugins/validation/entities/ItemValidation.ts
  src/services/item/plugins/validation/entities/ItemValidationGroup.ts
  src/services/item/plugins/validation/entities/itemValidationReview.ts
  src/services/item/plugins/validation/service.ts
  src/services/item/repository.ts
  src/services/item/service.ts
  src/services/item/test/fixtures/items.ts
  src/services/item/test/index.test.ts
  src/services/item/utils.ts
  src/services/itemLogin/entities/itemLogin.ts
  src/services/itemLogin/entities/itemLoginSchema.ts
  src/services/itemMembership/entities/ItemMembership.ts
  src/services/itemMembership/ws/events.ts
  src/services/member/entities/member.ts
  src/services/member/test/index.test.ts
  src/services/websockets/multi-instance.ts
  src/utils/config.ts
  src/utils/errors.ts
  test/migrations/migrations1679669193721/migrations.test.ts
  test/migrations/migrations1683637099103/migrations.test.ts
  test/migrations/migrations1689666251815/migrations.test.ts
  test/migrations/migrations1689777747530/migrations.test.ts
  yarn.lock
Labels: chore
