Repository graasp/graasp, pull requests merged in 2023-08, with the labels that each got.

#471 chore: cleanup env vars, add mailcatcher
  .devcontainer/docker-compose.yml
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/deploy-development.yml
  .github/workflows/test.yml
  README.md
  package.json
  src/app.ts
  src/plugins/datasource.ts
  src/plugins/decorator.ts
  src/plugins/mailer/index.ts
  src/services/action/services/action.ts
  src/services/action/utils/actions.test.ts
  src/services/action/utils/actions.ts
  src/services/auth/index.ts
  src/services/auth/plugins/magicLink/index.ts
  src/services/auth/plugins/magicLink/magicLink.test.ts
  src/services/auth/plugins/magicLink/repository.ts
  src/services/auth/plugins/password/index.ts
  src/services/auth/utils.ts
  src/services/chat/plugins/mentions/index.ts
  src/services/chat/plugins/mentions/service.ts
  src/services/item/plugins/action/index.ts
  src/services/item/plugins/action/requestExport/service.ts
  src/services/item/plugins/action/service.ts
  src/services/item/plugins/published/constants.ts
  src/services/itemMembership/index.ts
  src/services/itemMembership/service.ts
  src/services/utils.ts
  src/utils/config.ts
Labels: bug :beetle:, chore

#499 feat: replace mobile redirect with domain-based deep link
  .github/workflows/test.yml
  src/services/auth/plugins/magicLink/index.ts
  src/services/auth/plugins/magicLink/magicLink.test.ts
  src/services/auth/plugins/mobile/index.ts
  src/services/auth/plugins/mobile/mobile.test.ts
  src/services/invitation/constants.ts
  src/utils/config.ts
Labels: feature

#513 fix: return inherit item login schema, prevent put from child
  src/services/itemLogin/errors.ts
  src/services/itemLogin/repositories/itemLoginSchema.ts
  src/services/itemLogin/test/index.test.ts
Labels: bug :beetle:

#542 chore: add docs folder to dockerignore
  .dockerignore
Labels: documentation, chore

#539 feat: always redirect mobile auth to universal auth link
  src/services/auth/plugins/mobile/index.ts
  src/services/auth/plugins/mobile/mobile.test.ts
  src/services/auth/plugins/mobile/schemas.ts
  src/services/auth/service.ts
  src/utils/config.ts
Labels: feature

#559 fix: remove sentry profiling to resolve types
  package.json
  yarn.lock
Labels: bug :beetle:, build

#515 Broadcast apps data change events with websockets
  src/services/item/plugins/app/appAction/index.ts
  src/services/item/plugins/app/appAction/service.ts
  src/services/item/plugins/app/appData/index.ts
  src/services/item/plugins/app/appData/plugins/file/index.ts
  src/services/item/plugins/app/appData/service.ts
  src/services/item/plugins/app/appSetting/index.ts
  src/services/item/plugins/app/appSetting/plugins/file/index.ts
  src/services/item/plugins/app/appSetting/service.ts
  src/services/item/plugins/app/ws/events.ts
  src/services/item/plugins/app/ws/hooks.ts
  src/services/item/plugins/app/ws/utils.ts
Labels: feature, help wanted
