Repository graasp/graasp, pull requests merged in 2023-11, with the labels that each got.

#673 fix: filter sentry events at the source
  src/sentry.ts
Labels: bug :beetle:, priority

#680 fix: update to sdk 2.0.0
  package.json
  src/services/item/plugins/app/entities/app.ts
  src/services/item/plugins/app/entities/publisher.ts
  src/services/item/plugins/etherpad/test/service-api.test.ts
  src/services/item/plugins/html/h5p/index.ts
  src/services/item/plugins/html/h5p/service.ts
  src/services/item/plugins/published/plugins/search/meilisearch.ts
  src/services/item/plugins/published/test/index.test.ts
  src/services/item/service.ts
  src/services/item/test/index.test.ts
  src/services/item/ws/events.ts
  yarn.lock
Labels: bug :beetle:, chore

#684 fix: create getUrl and getFile in file repository
  package.json
  src/plugins/decorator.ts
  src/services/file/interfaces/fileRepository.ts
  src/services/file/repositories/local.ts
  src/services/file/repositories/s3.ts
  src/services/file/service.test.ts
  src/services/file/service.ts
  src/services/item/plugins/action/requestExport/service.ts
  src/services/item/plugins/app/appData/plugins/file/index.ts
  src/services/item/plugins/app/appData/plugins/file/service.ts
  src/services/item/plugins/app/appSetting/plugins/file/index.ts
  src/services/item/plugins/app/appSetting/plugins/file/service.ts
  src/services/item/plugins/file/index.ts
  src/services/item/plugins/file/service.ts
  src/services/item/plugins/file/test/index.test.ts
  src/services/item/plugins/html/h5p/index.ts
  src/services/item/plugins/html/h5p/service.ts
  src/services/item/plugins/html/h5p/test/utils.test.ts
  src/services/item/plugins/html/h5p/types.ts
  src/services/item/plugins/html/h5p/utils.ts
  src/services/item/plugins/html/service.ts
  src/services/item/plugins/importExport/constants.ts
  src/services/item/plugins/importExport/index.ts
  src/services/item/plugins/importExport/service.ts
  src/services/item/plugins/importExport/test/index.test.ts
  src/services/item/plugins/published/plugins/search/meilisearch.ts
  src/services/item/plugins/thumbnail/index.ts
  src/services/item/plugins/thumbnail/service.ts
  src/services/item/plugins/validation/service.ts
  src/services/member/plugins/thumbnail/index.ts
  src/services/member/plugins/thumbnail/service.ts
  src/services/thumbnail/service.ts
  yarn.lock
Labels: bug :beetle:, refactor

#657 feat: add a chatbot endpoint for apps (#641)
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/deploy-development.yml
  README.md
  package.json
  src/services/file/repositories/s3.ts
  src/services/item/plugins/app/chatBot/index.ts
  src/services/item/plugins/app/chatBot/interfaces/finishReason.ts
  src/services/item/plugins/app/chatBot/interfaces/gptVersion.ts
  src/services/item/plugins/app/chatBot/openAICompletion.ts
  src/services/item/plugins/app/chatBot/schemas.ts
  src/services/item/plugins/app/chatBot/service.ts
  src/services/item/plugins/app/chatBot/test/fixtures.ts
  src/services/item/plugins/app/chatBot/test/index.test.ts
  src/services/item/plugins/app/chatBot/utils.ts
  src/services/item/plugins/app/index.ts
  src/services/item/plugins/app/test/fixtures.ts
  src/utils/config.ts
  src/utils/errors.ts
  yarn.lock
Labels: feature

#697 fix: move back files from sdk
  package.json
  src/services/file/index.ts
  src/services/file/interfaces/configuration.ts
  src/services/file/repositories/local.ts
  src/services/file/repositories/s3.ts
  src/services/file/service.ts
  src/services/item/plugins/action/index.ts
  src/services/item/plugins/html/service.test.ts
  src/services/member/plugins/action/index.ts
  src/utils/config.ts
  yarn.lock
Labels: chore

#702 fix: update aws file for prod deploy
  .aws/graasp-prod.json
  .aws/graasp-stage.json
  .aws/refactor.json
Labels: build

#705 fix: rename deployment workflows
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
Labels: build

#687 fix: add missing client hosts and move workflows back here
  .aws/graasp-dev.json
  .aws/graasp-prod.json
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  .github/workflows/test.yml
  .prettierignore
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.6.3.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  README.md
  docker/Dockerfile
  package.json
  src/sentry.ts
  src/services/auth/plugins/magicLink/index.ts
  src/services/auth/plugins/password/index.ts
  src/services/auth/service.ts
  src/services/auth/utils.ts
  src/utils/config.ts
  yarn.lock
Labels: feature

#632 fix(app): use correct authentication method to deliver context
  src/services/item/plugins/app/appAction/test/fixtures.ts
  src/services/item/plugins/app/appData/test/fixtures.ts
  src/services/item/plugins/app/docs/api.md
  src/services/item/plugins/app/index.ts
  src/services/item/plugins/app/schemas.ts
  src/services/item/plugins/app/service.ts
  src/services/item/plugins/app/test/fixtures.ts
  src/services/item/plugins/app/test/index.test.ts
  src/services/item/plugins/etherpad/test/index.test.ts
  src/services/item/plugins/html/h5p/test/plugin.test.ts
  src/services/item/plugins/published/index.ts
  src/services/item/repository.ts
  src/services/item/service.ts
  test/app.ts
Labels: bug :beetle:, help wanted
