Repository graasp/graasp, pull requests merged in 2023-06, with the labels that each got.

#399 chore: delete postcheckout husky hook
  .husky/post-checkout
Labels: chore

#403 fix: prevent deletion of only / last admin on item
  src/services/itemMembership/service.ts
  src/services/itemMembership/test/index.test.ts
  src/utils/errors.ts
Labels: bug :beetle:

#457 fix: return creator for published items
  .devcontainer/docker-compose.yml
  .devcontainer/localstack/init.sh
  src/services/item/plugins/published/repositories/itemPublished.ts
Labels: bug :beetle:

#462 chore(ci): add auto-tag workflow
  .github/workflows/auto-tag.yml
  .github/workflows/release-please.yml
  .github/workflows/update-staging-version.yml
Labels: chore

#427 fix: getItemsByCategories only return root items
  src/services/item/plugins/published/repositories/itemPublished.ts
Labels: bug :beetle:

#467 feat: add etherpad features in core
  .github/workflows/test.yml
  package.json
  src/declarations.d.ts
  src/services/item/controller.ts
  src/services/item/index.ts
  src/services/item/plugins/etherpad/constants.ts
  src/services/item/plugins/etherpad/errors.ts
  src/services/item/plugins/etherpad/etherpad.ts
  src/services/item/plugins/etherpad/index.ts
  src/services/item/plugins/etherpad/schemas.ts
  src/services/item/plugins/etherpad/service-api.ts
  src/services/item/plugins/etherpad/service.ts
  src/services/item/plugins/etherpad/test/api.ts
  src/services/item/plugins/etherpad/test/service-api.test.ts
  src/services/item/plugins/etherpad/test/service.test.ts
  src/services/item/plugins/etherpad/test/utils.test.ts
  src/services/item/plugins/etherpad/types.ts
  src/services/item/plugins/etherpad/utils.ts
  src/services/item/plugins/h5p/test/config.ts
  src/services/item/plugins/h5p/test/plugin.test.ts
  src/services/item/repository.ts
  src/services/item/service.ts
  test/app.ts
  yarn.lock
Labels: feature

#408 fix: make membership websockets hooks work again
  src/declarations.d.ts
  src/services/item-memberships/ws/hooks.ts
  src/services/itemMembership/index.ts
  src/services/itemMembership/repository.ts
  src/services/itemMembership/service.ts
  src/services/itemMembership/ws/hooks.ts
Labels: feature
