Repository graasp/graasp, pull requests merged in 2023-01, with the labels that each got.

#293 fix: update plugin-thumbnails
  yarn.lock
Labels: chore

#295 feat: add etherpad service
  .devcontainer/db/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/etherpad/devApiKey.txt
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/cintegration-ecs-backend-caller.yml
  .github/workflows/nodejs.yml
  README.md
  db-schema-etherpad.sh
  package.json
  src/plugins/public.ts
  src/services/items/service-api.ts
  src/util/config.ts
  yarn.lock
Labels: feature

#299 fix: pin graasp-plugin-thumbnails and graasp-plugin-file-item
  package.json
  yarn.lock
Labels: bug

#302 fix: isolate transactions
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/cintegration-ecs-backend-caller.yml
  package.json
  src/services/global-task-runner.ts
  src/util/config.ts
  yarn.lock
Labels: bug

#317 ci: abort previously running jobs if newer version is running
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/cintegration-ecs-backend-caller.yml
  .github/workflows/nodejs.yml
Labels: build

#312 ci: split secrets and environment variables
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/cintegration-ecs-backend-caller.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
Labels: build

#315 feat: add sentry metrics
  .github/workflows/cdelivery-ecs-backend-caller.yml
  .github/workflows/cdeployment-ecs-backend-caller.yml
  .github/workflows/cintegration-ecs-backend-caller.yml
  package.json
  src/sentry.ts
  src/server.ts
  yarn.lock
Labels: feature

#319 fix: downgrade @sentry/profiling-node to 0.0.12
  package.json
  yarn.lock
Labels: bug
