Repository graasp/graasp, pull requests merged in 2024-02, with the labels that each got.

#812 fix: update readme values
  README.md
Labels: chore

#816 fix: use https in schemas
  src/plugins/mailer/layout.ts
  src/schemas/fluent-schema.ts
  src/schemas/global.ts
  src/services/chat/plugins/mentions/schemas.ts
  src/services/chat/schemas.ts
  src/services/invitation/schema.ts
  src/services/item/fluent-schema.ts
  src/services/item/plugins/action/schemas.ts
  src/services/item/plugins/action/test/index.test.ts
  src/services/item/plugins/app/appAction/schemas.ts
  src/services/item/plugins/app/appAction/test/fixtures.ts
  src/services/item/plugins/app/appData/plugins/file/schema.ts
  src/services/item/plugins/app/appData/schemas.ts
  src/services/item/plugins/app/appData/test/fixtures.ts
  src/services/item/plugins/app/appSetting/plugins/file/schema.ts
  src/services/item/plugins/app/appSetting/schemas.ts
  src/services/item/plugins/app/schemas.ts
  src/services/item/plugins/app/test/fixtures.ts
  src/services/item/plugins/embeddedLink/embeddedLink.test.ts
  src/services/item/plugins/etherpad/schemas.ts
  src/services/item/plugins/file/schema.ts
  src/services/item/plugins/geolocation/schemas.ts
  src/services/item/plugins/html/h5p/schemas.ts
  src/services/item/plugins/importExport/schema.ts
  src/services/item/plugins/itemCategory/schemas.ts
  src/services/item/plugins/itemFavorite/schemas.ts
  src/services/item/plugins/itemFlag/schemas.ts
  src/services/item/plugins/itemLike/schemas.ts
  src/services/item/plugins/itemTag/schemas.ts
  src/services/item/plugins/published/schemas.ts
  src/services/item/plugins/recycled/schemas.ts
  src/services/item/plugins/thumbnail/schemas.ts
  src/services/item/plugins/validation/schemas.ts
  src/services/itemMembership/schemas.ts
  src/services/member/plugins/profile/schemas.ts
  src/services/member/plugins/thumbnail/schemas.ts
  src/services/member/schemas.ts
Labels: chore

#822 docs: testing env and localstack issues
  README.md
Labels: documentation

#819 fix: return 200 with `null` when item is not published instead of error
  src/services/item/plugins/published/schemas.ts
  src/services/item/plugins/published/service.ts
  src/services/item/plugins/published/test/index.test.ts
Labels: improvement

#828 fix: update sdk dep and schemas
  package.json
  src/services/item/plugins/document/schemas.ts
  yarn.lock
Labels: dependencies

#846 fix: change smtp config to string
  .devcontainer/docker-compose.yml
Labels: bug :beetle:, chore
