Repository graasp/graasp, pull requests merged in 2024-10, with the labels that each got.

#1479 fix: app actions structure is wrong for export
  src/services/action/utils/export-utils.test.ts
  src/services/action/utils/export.ts
  src/services/auth/plugins/password/index.ts
  src/services/item/plugins/action/index.ts
  src/services/item/plugins/action/schemas.ts
  src/services/item/plugins/action/service.ts
  src/services/member/controller.test.ts
  src/services/member/controller.ts
  src/services/member/plugins/thumbnail/index.ts
Labels: bug :beetle:

#1432 chore(main): release 1.53.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1467 fix: save membership on item login schema item on item login
  .github/workflows/test.yml
  package.json
  src/services/itemLogin/service.ts
  src/services/itemLogin/test/index.test.ts
  yarn.lock
Labels: bug :beetle:

#1499 fix: remove dependency to fix deploy
  docker/Dockerfile
  package.json
  src/services/item/plugins/embeddedLink/utils.ts
  yarn.lock
Labels: bug :beetle:, dependencies

#1495 chore(main): release 1.53.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1512 fix: update core container log group to match infra
  .aws/graasp-dev.json
Labels: build

#1505 fix: remove unused route `PATCH /items`
  src/services/item/controller.ts
  src/services/item/plugins/action/service.test.ts
  src/services/item/plugins/action/service.ts
  src/services/item/plugins/document/document.test.ts
  src/services/item/plugins/embeddedLink/test/embeddedLink.test.ts
  src/services/item/schema.ts
  src/services/item/service.ts
  src/services/item/test/index.update.test.ts
  src/services/item/test/ws.test.ts
Labels: optimization, internal

#1518 fix: extract nudenet and iframely as separate services
  .aws/graasp-dev.json
Labels: build

#1517 test: use only one build for tests
  src/services/action/repositories/action.test.ts
  src/services/chat/plugins/mentions/repository.test.ts
  src/services/chat/test/chatMessage.test.ts
  src/services/item/plugins/enroll/index.test.ts
  src/services/item/plugins/invitation/test/index.test.ts
  src/services/item/plugins/itemFlag/test/index.test.ts
  src/services/item/plugins/itemTag/test/index.test.ts
  src/services/item/plugins/recycled/test/index.test.ts
  src/services/itemLogin/test/index.test.ts
Labels: testing

#1519 build: update task defs for stage and prod
  .aws/graasp-dev.json
  .aws/graasp-prod.json
  .aws/graasp-stage.json
Labels: build

#1520 refactor: have only one build for item tests
  src/services/item/test/index.read.test.ts
  src/services/item/test/index.update.test.ts
Labels: refactor, testing

#1521 refactor: use one build per tests
  src/services/authorization.test.ts
  src/services/chat/test/chatMention.test.ts
  src/services/item/plugins/document/document.test.ts
  src/services/item/plugins/file/test/index.test.ts
  src/services/item/plugins/geolocation/index.test.ts
  src/services/item/plugins/importExport/service.test.ts
  src/services/item/plugins/importExport/test/index.test.ts
  src/services/item/plugins/publication/published/test/index.test.ts
  src/services/item/test/index.update.test.ts
Labels: refactor, testing

#1526 refactor: refactor tests to use one app build
  src/services/action/services/action.test.ts
  src/services/item/plugins/action/service.test.ts
  src/services/item/plugins/action/test/index.test.ts
  src/services/item/plugins/itemFavorite/test/index.test.ts
  src/services/item/plugins/publication/validation/test/index.test.ts
Labels: refactor, testing

#1533 fix: password reset token should be single use
  src/services/auth/plugins/password/index.test.ts
  src/services/auth/plugins/password/service.ts
Labels: bug :beetle:

#1535 fix: do not encode redirection url for password
  src/services/auth/plugins/password/index.test.ts
  src/services/auth/plugins/password/index.ts
Labels: bug :beetle:

#1503 chore(main): release 1.54.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1546 fix: set html as optional for link metadata
  src/services/item/plugins/embeddedLink/schemas.ts
  src/services/item/plugins/embeddedLink/test/controller.test.ts
Labels: bug :beetle:

#1548 chore(main): release 1.54.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1555 chore(main): release 1.54.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1558 fix: put nudenet back in container
  .aws/graasp-dev.json
  .aws/graasp-prod.json
  .aws/graasp-stage.json
Labels: bug :beetle:, build

#1552 fix: fix packed tag
  src/services/account/repository.test.ts
  src/services/item/ItemWrapper.test.ts
  src/services/item/ItemWrapper.ts
  src/services/item/plugins/itemTag/test/fixtures.ts
Labels: bug :beetle:

#1289 fix: new email builder and title escape fix
  src/plugins/mailer/builder.ts
  src/plugins/mailer/langs/ar.json
  src/plugins/mailer/langs/constants.ts
  src/plugins/mailer/langs/de.json
  src/plugins/mailer/langs/en.json
  src/plugins/mailer/langs/es.json
  src/plugins/mailer/langs/fr.json
  src/plugins/mailer/langs/it.json
  src/plugins/mailer/service.ts
  src/plugins/mailer/test/index.test.ts
  src/services/auth/plugins/magicLink/magicLink.test.ts
  src/services/auth/plugins/magicLink/service.ts
  src/services/auth/plugins/mobile/mobile.test.ts
  src/services/auth/plugins/mobile/service.ts
  src/services/auth/plugins/password/index.test.ts
  src/services/auth/plugins/password/service.ts
  src/services/auth/service.ts
  src/services/chat/plugins/mentions/service.ts
  src/services/chat/test/chatMessage.test.ts
  src/services/item/plugins/action/requestExport/service.ts
  src/services/item/plugins/action/test/index.test.ts
  src/services/item/plugins/invitation/service.ts
  src/services/item/plugins/invitation/test/index.test.ts
  src/services/item/plugins/publication/published/service.ts
  src/services/item/plugins/publication/published/test/index.test.ts
  src/services/itemMembership/plugins/MembershipRequest/index.test.ts
  src/services/itemMembership/plugins/MembershipRequest/service.ts
  src/services/itemMembership/service.ts
  src/services/itemMembership/test/index.test.ts
  src/services/member/controller.test.ts
  src/services/member/plugins/export-data/test/index.test.ts
  src/services/member/plugins/export-data/utils/export.utils.ts
  src/services/member/service.ts
  test/utils.ts
Labels: bug :beetle:

#1576 feat: add health endpoint
  src/plugins/meta.ts
Labels: chore

#1575 fix: setup single db instance
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .vscode/settings.json
  README.md
  bootstrapDB.sql
Labels: build, chore

#1578 fix: add env var for account
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
Labels: bug :beetle:

#1563 chore(main): release 1.55.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1590 chore(main): release 1.56.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
