Repository graasp/graasp, pull requests merged in 2024-04, with the labels that each got.

#891 feat: add display name column
  package.json
  src/migrations/1711101133700-add-item-display-name.ts
  src/services/item/entities/Item.ts
  src/services/item/fluent-schema.ts
  src/services/item/repository.ts
  yarn.lock
Labels: feature

#927 fix: flacky websockets test
  src/services/item/plugins/recycled/test/ws.test.ts
  src/services/item/test/ws.test.ts
Labels: chore, testing

#926 fix: deploy workflow checkout
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
Labels: bug :beetle:

#700 feat: import users with CSV and create file structure based on groups in CSV
  .devcontainer/devcontainer.json
  .gitignore
  .prettierrc
  API Collections/Auth/Mobile/Auth.bru
  API Collections/Auth/Mobile/Refresh Token.bru
  API Collections/Auth/Mobile/Register.bru
  API Collections/Auth/Mobile/Sign In.bru
  API Collections/Auth/Web/Auth (magic link).bru
  API Collections/Auth/Web/Logout.bru
  API Collections/Auth/Web/Register.bru
  API Collections/Auth/Web/Sign In.bru
  API Collections/Invitations/All Item Invitations.bru
  API Collections/Invitations/Single Invitation.bru
  API Collections/Invitations/Upload Template users csv.bru
  API Collections/Invitations/Upload users csv.bru
  API Collections/Item/Accessible.bru
  API Collections/Item/Get Item.bru
  API Collections/Item/Memberships/Delete membership.bru
  API Collections/Item/Memberships/Get Item memberships.bru
  API Collections/Member/Current Member.bru
  API Collections/Zip/Import zip.bru
  API Collections/bruno.json
  API Collections/collection.bru
  API Collections/environments/Dev.bru
  API Collections/environments/Graasp Local.bru
  package.json
  src/plugins/__mocks__/datasource.ts
  src/plugins/datasource.ts
  src/plugins/decorator.ts
  src/services/invitation/errors.ts
  src/services/invitation/service.ts
  src/services/item/index.ts
  src/services/item/plugins/invitation/constants.ts
  src/services/item/plugins/invitation/entity.ts
  src/services/item/plugins/invitation/errors.ts
  src/services/item/plugins/invitation/index.ts
  src/services/item/plugins/invitation/repository.ts
  src/services/item/plugins/invitation/schema.ts
  src/services/item/plugins/invitation/service.ts
  src/services/item/plugins/invitation/specifications.md
  src/services/item/plugins/invitation/test/fixtures/invalid-no-email.csv
  src/services/item/plugins/invitation/test/fixtures/single-user.csv
  src/services/item/plugins/invitation/test/fixtures/users-groups.csv
  src/services/item/plugins/invitation/test/fixtures/users.csv
  src/services/item/plugins/invitation/test/index.test.ts
  src/services/item/plugins/invitation/utils.test.ts
  src/services/item/plugins/invitation/utils.ts
  src/services/item/test/ws.test.ts
  src/services/itemMembership/index.ts
  src/services/itemMembership/specifications.md
  src/services/member/service.ts
  src/utils/repositories.ts
  yarn.lock
Labels: feature

#931 fix: add poolsize in env
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  src/plugins/datasource.ts
Labels: build

#930 fix: workflows again
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
Labels: bug :beetle:, ci

#941 fix: password login should return `MemberNotSignedUp` if email has no account
  src/services/auth/plugins/magicLink/magicLink.test.ts
  src/services/auth/plugins/password/service.ts
  src/services/auth/plugins/password/test/password.test.ts
Labels: bug :beetle:

#959 fix: optimize get published collections for member
  src/services/item/plugins/published/plugins/search/meilisearch.ts
  src/services/item/plugins/published/repositories/itemPublished.test.ts
  src/services/item/plugins/published/repositories/itemPublished.ts
  src/services/item/plugins/published/service.ts
  src/services/item/plugins/published/test/index.test.ts
  src/services/item/plugins/published/test/meilisearch.test.ts
  src/services/item/repository.test.ts
  src/services/item/repository.ts
  src/services/item/test/fixtures/items.ts
  src/utils/repositories.ts
Labels: improvement, optimization

#973 fix: copy item thumbnails
  docker.env
  package.json
  src/declarations.d.ts
  src/plugins/decorator.ts
  src/services/action/services/action.test.ts
  src/services/item/entities/Item.ts
  src/services/item/plugins/action/service.test.ts
  src/services/item/plugins/file/index.ts
  src/services/item/plugins/file/service.ts
  src/services/item/plugins/geolocation/service.test.ts
  src/services/item/plugins/importExport/service.ts
  src/services/item/plugins/published/test/index.test.ts
  src/services/item/plugins/thumbnail/index.ts
  src/services/item/plugins/thumbnail/service.ts
  src/services/item/service.test.ts
  src/services/item/service.ts
  src/services/item/test/fixtures/items.ts
  src/services/thumbnail/service.ts
  tsconfig.build.json
  tsconfig.json
  tsconfig.test.json
Labels: bug :beetle:

#976 fix: apply user name limits
  src/schemas/global.ts
  src/schemas/globals.test.ts
  src/services/auth/plugins/magicLink/magicLink.test.ts
  src/services/auth/plugins/magicLink/schemas.ts
  src/services/member/schemas.ts
  src/services/member/test/index.test.ts
Labels: chore

#979 fix: upgrade gpt versions
  package.json
  src/services/item/plugins/app/chatBot/index.ts
  src/services/item/plugins/app/chatBot/interfaces/gptVersion.ts
  src/services/item/plugins/app/chatBot/openAICompletion.ts
  src/services/item/plugins/app/chatBot/schemas.ts
  src/services/item/plugins/app/chatBot/service.ts
  src/services/item/plugins/app/chatBot/test/index.test.ts
  src/services/item/plugins/app/chatBot/utils.ts
  src/utils/config.ts
  yarn.lock
Labels: improvement

#991 fix: include maxwidth in settings schema
  src/services/item/fluent-schema.ts
  src/services/item/plugins/file/test/index.test.ts
Labels: bug :beetle:
