Repository graasp/graasp, pull requests merged in 2024-11, with the labels that each got.

#1607 docs: add documentation for short links
  src/services/item/plugins/shortLink/schemas.ts
Labels: documentation

#1606 chore(main): release 1.56.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1628 feat: add temperature in query params for chatbot API
  src/services/item/plugins/app/chatBot/index.ts
  src/services/item/plugins/app/chatBot/openAICompletion.ts
  src/services/item/plugins/app/chatBot/schemas.ts
  src/services/item/plugins/app/chatBot/service.ts
  src/services/item/plugins/app/chatBot/test/index.test.ts
  src/services/item/plugins/app/chatBot/utils.ts
  src/utils/config.ts
Labels: feature

#1622 chore(main): release 1.57.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1643 chore(main): release 1.58.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
