Repository graasp/graasp, pull requests merged in 2024-03, with the labels that each got.

#852 feat: add descriptionPlacement support in item settings
  package.json
  src/services/item/fluent-schema.ts
  src/services/item/repository.ts
  src/services/item/test/index.test.ts
  yarn.lock
Labels: feature

#863 feat: allow members with read access to post app data for another member
  src/services/item/plugins/app/appData/service.ts
  src/services/item/plugins/app/appData/test/index.test.ts
  src/services/item/plugins/app/docs/api.md
  src/services/item/test/index.test.ts
Labels: feature

#878 fix: add showLinkIframe and showLinkButton in settings with tests
  src/services/item/fluent-schema.ts
  src/services/item/plugins/embeddedLink/embeddedLink.test.ts
  src/services/item/plugins/embeddedLink/index.ts
  src/services/item/plugins/file/service.ts
  src/services/item/test/fixtures/items.ts
  src/services/item/test/index.test.ts
Labels: bug :beetle:

#884 fix(ci): add merge group
  .github/workflows/test.yml
Labels: ci

#886 fix: return null when public profile is not visible
  src/services/member/plugins/profile/controller.ts
  src/services/member/plugins/profile/repository.ts
  src/services/member/plugins/profile/service.ts
  src/services/member/plugins/profile/test/index.test.ts
Labels: improvement

#887 feat: add more status reports on `/status`
  jest.config.js
  src/plugins/meta.ts
  src/services/item/plugins/published/plugins/search/meilisearch.ts
  src/services/item/plugins/published/plugins/search/service.ts
  yarn.lock
Labels: feature

#890 fix: update syntax for set-output in test workflow
  .github/workflows/test.yml
Labels: chore

#897 fix: add CORS on status endpoint
  src/plugins/meta.ts
Labels: bug :beetle:

#903 fix: do not expose port 1025 to the local machine
  .devcontainer/docker-compose.yml
Labels: build, chore

#877 feat: add helper label for geoloc
  package.json
  src/migrations/1710334646869-geolocation-helper-label.ts
  src/services/file/repositories/s3.ts
  src/services/item/plugins/geolocation/ItemGeolocation.ts
  src/services/item/plugins/geolocation/index.ts
  src/services/item/plugins/geolocation/repository.test.ts
  src/services/item/plugins/geolocation/repository.ts
  src/services/item/plugins/geolocation/schemas.ts
  src/services/item/plugins/geolocation/service.ts
  yarn.lock
Labels: improvement
