Repository graasp/graasp, pull requests merged in 2024-01, with the labels that each got.

#737 fix: return shared child in accessible items
  src/services/item/test/index.test.ts
  src/services/itemMembership/repository.ts
Labels: bug :beetle:

#745 fix: add test tsconfig and update type-check command
  package.json
  tsconfig.test.json
Labels: chore

#740 fix: add logger to fileService
  src/plugins/decorator.ts
  src/services/file/index.ts
  src/services/file/interfaces/fileRepository.ts
  src/services/file/repositories/s3.ts
  src/services/file/service.test.ts
  src/services/file/service.ts
  src/services/item/plugins/html/h5p/service.ts
  src/services/item/plugins/html/service.test.ts
  src/services/item/plugins/html/service.ts
  src/services/item/plugins/importExport/index.ts
  src/services/item/plugins/importExport/service.ts
Labels: chore

#755 fix: disable bad words validation
  src/services/item/plugins/recycled/test/ws.test.ts
  src/services/item/plugins/validation/processes/badWordsDetection.test.ts
  src/services/item/plugins/validation/processes/badWordsDetection.ts
  src/services/item/plugins/validation/service.ts
  src/services/item/test/ws.test.ts
Labels: bug :beetle:

#757 fix: do not fail login with password if score is low
  src/declarations.d.ts
  src/services/auth/plugins/captcha/index.ts
  src/services/auth/plugins/mobile/index.ts
  src/services/auth/plugins/mobile/mobile.test.ts
  src/services/auth/plugins/password/index.ts
  src/services/auth/plugins/password/test/password.test.ts
Labels: improvement

#752 feat: include app data, setting and actions in analytics
  src/services/action/utils/export.test.ts
  src/services/action/utils/export.ts
  src/services/item/plugins/action/base-analytics.test.ts
  src/services/item/plugins/action/base-analytics.ts
  src/services/item/plugins/action/schemas.ts
  src/services/item/plugins/action/service.ts
  src/services/item/plugins/action/test/index.test.ts
  src/services/item/plugins/app/appAction/test/index.test.ts
  src/services/item/plugins/app/appData/test/index.test.ts
  src/services/item/plugins/app/appSetting/test/index.test.ts
Labels: feature

#771 fix: normalise invitation email
  src/services/invitation/repository.ts
  src/services/invitation/service.ts
  src/services/invitation/test/index.test.ts
Labels: bug :beetle:

#784 fix: flacky recycle feedback test
  src/services/item/plugins/recycled/test/ws.test.ts
Labels: chore, ci
