Repository graasp/graasp, pull requests merged in 2024-07, with the labels that each got.

#1133 fix: fix deploy files for email var
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
Labels: bug :beetle:

#1137 chore: add missing env var error, for better DX
  src/utils/config.ts
  src/utils/errors.ts
Labels: improvement

#1186 fix: add email in link for email update
  src/services/auth/plugins/passport/constants.ts
  src/services/member/schemas.ts
  src/services/member/service.ts
Labels: bug :beetle:

#1204 fix: remove leaked information and remove unused errors
  .devcontainer/docker-compose.yml
  src/services/auth/plugins/mobile/mobile.test.ts
  src/services/auth/plugins/passport/strategies/emailChange.ts
  src/services/auth/plugins/passport/strategies/jwt.ts
  src/services/auth/plugins/passport/strategies/jwtChallengeVerifier.ts
  src/services/auth/plugins/passport/strategies/magicLink.ts
  src/services/auth/plugins/passport/strategies/passwordReset.ts
  src/services/auth/plugins/password/repository.ts
  src/services/auth/plugins/password/service.ts
  src/services/chat/errors.ts
  src/services/chat/plugins/mentions/service.ts
  src/services/chat/service.ts
  src/services/chat/test/chatMention.test.ts
  src/services/chat/test/chatMessage.test.ts
  src/services/file/service.ts
  src/services/item/controller.ts
  src/services/item/plugins/action/requestExport/service.ts
  src/services/item/plugins/app/appSetting/service.ts
  src/services/item/plugins/html/service.ts
  src/services/item/plugins/invitation/index.ts
  src/services/item/plugins/invitation/service.ts
  src/services/item/plugins/itemCategory/repositories/itemCategory.ts
  src/services/item/plugins/itemFavorite/index.ts
  src/services/item/plugins/itemFavorite/services/favorite.ts
  src/services/item/plugins/itemLike/index.ts
  src/services/item/plugins/itemLike/service.ts
  src/services/item/plugins/published/index.ts
  src/services/item/plugins/published/service.ts
  src/services/item/plugins/recycled/index.ts
  src/services/item/plugins/recycled/service.ts
  src/services/item/plugins/shortLink/repository.ts
  src/services/item/repository.test.ts
  src/services/item/repository.ts
  src/services/item/service.ts
  src/services/item/test/index.test.ts
  src/services/itemLogin/index.ts
  src/services/itemLogin/service.ts
  src/services/itemMembership/index.ts
  src/services/itemMembership/repository.ts
  src/services/itemMembership/service.ts
  src/services/itemMembership/test/index.test.ts
  src/services/member/controller.ts
  src/services/member/plugins/action/index.ts
  src/services/member/plugins/action/service.ts
  src/services/member/plugins/action/test/service.test.ts
  src/services/member/plugins/export-data/controller.ts
  src/services/member/plugins/export-data/service.ts
  src/services/member/plugins/profile/repository.ts
  src/services/member/repository.ts
  src/services/member/service.ts
  src/services/member/test/index.test.ts
  src/utils/errors.ts
Labels: bug :beetle:

#1238 fix: lift up Pagination types and use ones defined in sdk
  package.json
  src/services/item/controller.ts
  src/services/item/plugins/publication/publicationState/publicationState.ts
  src/services/item/plugins/publication/publicationState/test/publicationState.test.ts
  src/services/item/service.ts
  src/services/itemMembership/repository.ts
  src/types.ts
  yarn.lock
Labels: chore

#1245 fix: fix where scope on search
  src/services/item/plugins/geolocation/repository.ts
  src/services/item/repository.ts
  src/services/item/test/index.test.ts
  src/services/itemMembership/repository.ts
Labels: bug :beetle:, priority

#1236 feat: add member password routes (POST and update PATCH)
  package.json
  src/plugins/datasource.ts
  src/services/auth/plugins/password/errors.ts
  src/services/auth/plugins/password/index.test.ts
  src/services/auth/plugins/password/index.ts
  src/services/auth/plugins/password/repository.ts
  src/services/auth/plugins/password/schemas.ts
  src/services/auth/plugins/password/service.ts
  src/services/auth/plugins/password/test/fixtures/password.ts
  src/services/auth/plugins/password/utils.ts
  src/utils/config.ts
  src/utils/errors.ts
  src/utils/repositories.ts
  test/utils.ts
  yarn.lock
Labels: feature

#1250 fix: log group in dev should be `ecs/graasp`
  .aws/graasp-dev.json
  .devcontainer/docker-compose.yml
Labels: build

#1241 chore(main): release 1.46.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
