Repository graasp/graasp, pull requests merged in 2024-09, with the labels that each got.

#1328 chore(main): release 1.48.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1379 chore(main): release 1.49.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1401 fix: set jest extension to run on-demand instead of watch
  .vscode/settings.json
Labels: chore

#1399 fix: deprecate patch member use current member instead
  src/services/member/controller.ts
  src/services/member/schemas.ts
  src/services/member/test/index.test.ts
Labels: improvement

#1404 chore: update code to fix sonar cloud issue
  src/services/itemMembership/repository.ts
  src/services/itemMembership/utils.ts
Labels: chore, internal

#1400 chore(main): release 1.50.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1420 chore(main): release 1.50.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1427 chore(main): release 1.50.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1428 chore(main): release 1.51.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1429 chore(main): release 1.52.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
