Repository graasp/graasp, pull requests merged in 2025-05, with the labels that each got.

#1850 chore(main): release 2.2.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1859 chore(main): release 2.3.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1869 fix: improve schemas for item_packed.thumbnails and search hits
  package.json
  src/services/item/item.schemas.packed.ts
  src/services/item/plugins/importExport/test/index.test.ts
  src/services/item/plugins/publication/published/plugins/search/meilisearch.ts
  src/services/item/plugins/publication/published/plugins/search/search.schemas.ts
  src/services/item/plugins/publication/published/plugins/search/search.service.ts
  src/services/item/plugins/tag/ItemTag.repository.test.ts
  src/services/item/plugins/tag/itemTag.service.ts
  src/services/tag/tag.repository.test.ts
  src/services/tag/tag.repository.ts
  yarn.lock
Labels: chore

#1864 fix: allow to post twice a like on an item
  src/services/item/plugins/itemLike/itemLike.controller.test.ts
  src/services/item/plugins/itemLike/itemLike.controller.ts
  src/services/item/plugins/itemLike/itemLike.repository.ts
  src/services/item/plugins/itemLike/itemLike.schemas.ts
Labels: bug :beetle:
