Repository graasp/graasp, pull requests merged in 2025-06, with the labels that each got.

#1878 chore(sonar-cloud): use a fixed tag for the builder base image in the migration docker file
  docker/migrate.Dockerfile
Labels: build, chore

#1883 fix: add endpoint for featured collections
  .github/workflows/test.yml
  src/services/item/plugins/publication/published/plugins/search/search.controller.test.ts
  src/services/item/plugins/publication/published/plugins/search/search.controller.ts
  src/services/item/plugins/publication/published/plugins/search/search.schemas.ts
  src/services/item/plugins/publication/published/plugins/search/search.service.test.ts
  src/services/item/plugins/publication/published/plugins/search/search.service.ts
  src/utils/config.ts
Labels: improvement

#1890 fix(opti): remove join on accountsTable for `getInheritedMany`
  package.json
  src/services/itemMembership/membership.repository.ts
Labels: chore

#1870 chore(main): release 2.4.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1894 fix: some typo in the readme
  README.md
Labels: chore

#1899 chore: remove git blame extension from dev container as it is now standard
  .devcontainer/devcontainer.json
Labels: chore

#1902 chore: split configs
  src/app.ts
  src/config/env.ts
  src/config/helpers.ts
  src/config/mailer.ts
  src/config/redis.ts
  src/config/secrets.ts
  src/di/container.ts
  src/fastify.ts
  src/jobs.ts
  src/sentry.ts
  src/services/auth/auth.service.ts
  src/services/auth/plugins/captcha/captcha.ts
  src/services/auth/plugins/magicLink/magicLink.controller.test.ts
  src/services/auth/plugins/passport/plugin.test.ts
  src/services/auth/plugins/passport/plugin.ts
  src/services/auth/plugins/passport/strategies/emailChange.ts
  src/services/auth/plugins/passport/strategies/jwtApps.ts
  src/services/auth/plugins/passport/strategies/jwtChallengeVerifier.ts
  src/services/auth/plugins/passport/strategies/passwordReset.ts
  src/services/auth/plugins/password/password.controller.test.ts
  src/services/auth/plugins/password/password.controller.ts
  src/services/auth/plugins/password/password.service.ts
  src/services/auth/plugins/password/utils.ts
  src/services/auth/utils.ts
  src/services/authentication.ts
  src/services/item/index.ts
  src/services/item/plugins/app/app.service.ts
  src/services/item/plugins/etherpad/etherpad.controller.ts
  src/services/member/member.controller.email.storage.test.ts
  src/services/member/member.service.ts
  src/services/websockets/test/test-utils.ts
  src/services/websockets/websocket.controller.ts
  src/utils/assertions.ts
  src/utils/config.ts
  src/utils/errors.ts
Labels: chore

#1903 fix: display thumbnail failure reason as JSON.stringified
  src/services/item/plugins/thumbnail/itemThumbnail.service.ts
Labels: bug :beetle:, chore

#1919 fix: add strict facetName schema from filterable attributes
  src/services/item/plugins/publication/published/plugins/search/meilisearch.ts
  src/services/item/plugins/publication/published/plugins/search/search.constants.ts
  src/services/item/plugins/publication/published/plugins/search/search.controller.test.ts
  src/services/item/plugins/publication/published/plugins/search/search.schemas.ts
Labels: improvement

#1920 fix: action.view migration to remove `explorer` and add `home` and `analytics`
  package.json
  src/drizzle/0007_action_view_enum.sql
  src/drizzle/meta/0007_snapshot.json
  src/drizzle/meta/_journal.json
  src/drizzle/schema.ts
  src/services/action/action.service.ts
  src/services/item/plugins/action/itemAction.schemas.ts
  yarn.lock
Labels: bug :beetle:, chore
