Repository graasp/graasp, pull requests merged in 2025-02, with the labels that each got.

#1741 fix: apply rightsizing recomendations
  .aws/graasp-dev.json
  .aws/graasp-stage.json
Labels: build

#1745 fix: replace non breaking spaces from link metadata title
  src/services/item/plugins/embeddedLink/service.test.ts
  src/services/item/plugins/embeddedLink/service.ts
Labels: bug :beetle:

#1716 chore(main): release 1.62.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1755 chore(main): release 1.63.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
