Repository graasp/graasp, pull requests merged in 2025-07, with the labels that each got.

#1923 chore(main): release 2.5.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1933 fix: remove legacy push action to graasp-deploy
  .github/workflows/release-please.yml
Labels: ci

#1934 fix: remove unused configuration and decoration for the file service
  src/services/item/index.ts
  src/services/item/plugins/file/itemFile.controller.ts
Labels: chore

#1942 fix: code smell with nested template string
  test/factories/item.factory.ts
Labels: chore
