Repository graasp/graasp, pull requests merged in 2025-04, with the labels that each got.

#1813 fix: release please workflow
  .github/actions/build-images/action.yml
  .github/workflows/release-please.yml
Labels: bug :beetle:

#1803 chore(main): release 2.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1830 fix: convert timestamp columns to include timezone
  src/drizzle/0003_use-timezone-in-items-account.sql
  src/drizzle/meta/0003_snapshot.json
  src/drizzle/meta/_journal.json
  src/drizzle/schema.ts
Labels: bug :beetle:

#1826 chore(main): release 2.0.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1831 chore(main): release 2.0.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1836 fix: read replica env vars
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  README.md
  src/drizzle/db.ts
  src/utils/config.ts
Labels: bug :beetle:

#1837 chore(main): release 2.0.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1774 fix: setup init script for DB in container
  .devcontainer/docker-compose.yml
  bootstrapDB.sql
Labels: bug :beetle:

#1841 chore(main): release 2.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1849 chore(main): release 2.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1835 fix: auto-deploy
  .github/actions/build-images/action.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/release-please.yml
  docker/Dockerfile
  docker/auth.sh
  docker/build.sh
  docker/compose.yml
  src/plugins/meta.ts
  src/utils/config.ts
Labels: build
